### ISSUE TITLE
Plugin doesnt start

### ISSUE THREAD

**Issue by VipelyRS** [MiraculixxT/Veinminer#16]
idk it kinda just dies
https://pastebin.com/xX8RW9av

plugins:
<img width="456" alt="image" src="https://github.com/user-attachments/assets/d1dc6a7f-7543-438f-8b65-e4c0384feb8a">
<img width="456" alt="image" src="https://github.com/user-attachments/assets/49870914-bc4c-4abe-a456-3885a2623d78">

**Comment by MiraculixxT** [comment]
Paper implemented the custom enchantment API first in 1.21.1, not 1.21. It should be save to update, as 1.21.1 only internal and security changes.

**Comment by VipelyRS** [comment]
ah alright, thank you!
