### ISSUE TITLE
veinminer 2.1.2 crashes on enable and disable

### ISSUE THREAD

**Issue by approachcircle** [MiraculixxT/Veinminer#9]
when enabled or disabled, it throws this exception:

![image](https://github.com/user-attachments/assets/12d97d41-4d3c-41c0-9fba-12f46d6616bb)

**Comment by MiraculixxT** [comment]
Could you share your Minecraft version and perhaps the full log?

**Comment by approachcircle** [comment]
minecraft version is 1.21.1, and i'll provide the latest log file later when i can

**Comment by approachcircle** [comment]
latest log is here:

[latest.log](https://github.com/user-attachments/files/16573886/latest.log)

**Comment by MiraculixxT** [comment]
The latest version is not compatible with 1.21.1
Only the exact shown version range is supported. I'll release an update soon

**Comment by approachcircle** [comment]
alright, i appreciate it
